- kod/object/active/holder/nomoveon/battler/player.kod
- kod/util/qormas.kod
Check for who = $ before running present IP code.
> Add $ checks to qormas. Separate Qormas decoration removal into its own message, which can be called on its own to remove decorations.

- kod/object/passive/trestype/ghostt.kod
Just a small spacing fix to neatin the file up
> a small spacing fix

- kod/object/active/holder/nomoveon/battler/monster/troop.kod
Should work 100% properly, Did for me
> Npc soldiers

- patcher/ClientPatcher/ClientPatchForm.Designer.cs
- patcher/ClientPatcher/ClientPatchForm.cs
- patcher/ClientPatcher/ClientPatcher.cs
- patcher/ClientPatcher/ClientPatcher.csproj
- patcher/Patcher.sln
Patcher now caches the md5 sums of local files to speed up launching the game.
Verify files button added under options to re-generate the local cache.
> Finished Cache support for the patcher.

- kod/object/passive/heatshimmer.kod
- kod/object/passive/makefile
We probably need something with angles, since this rotates as the user moves around it.
> Add heatshimmer wall for desert.

- kod/object/active/holder/nomoveon/battler/player.kod
- kod/object/passive/spell/atakspel.kod
- kod/object/passive/spell/debuff/makefile
- kod/object/passive/spell/makefile
- kod/object/passive/spell/persench/anon.kod
- kod/object/passive/spell/persench/focus.kod
- kod/object/passive/spell/persench/makefile
- kod/object/passive/spell/radiusench/makefile
These two spells were still in the Spell class. Moved them to the PersonalEnchantment class.
Mana Focus cast time lowered from 7 seconds to 3.
Anonymity PE description will display the time remaining, Mana Focus PE will display the spellpower at which it was cast.
Also formatted the makefiles in Spell and PersonalEnchantment to have less spells on each line, to reduce the chances of line conflicts with two or more people working in the directories in the same update.
> Move Anonymity and Mana Focus to PersonalEnchantment, lower Mana Focus cast time from 7 seconds to 3.

- kod/object/active/holder/nomoveon/battler/player/user.kod
Need to add the new MM_MONSTER minimap flag for morphed players.
> Fix invisible morph dots.

- kod/object/passive/itematt/weapatt/wavamper.kod
Bringing it in line with other weapon attributes. Added min/max health gained as properties so if we ever need to adjust them in-game, we can.
> Remove karma requirement from vamp weapon attribute.

- kod/object/active/holder/room/monsroom/objroom/k5.kod
Moved it out of the wall (28,50 to 28.49). Also cleaned up the file a bit.
> Fix spawn point in wall in Badlands 2.

- kod/object/active/holder/room/monsroom/survivalroom.kod
Should be KraananCharm, not SteelTorc
> Fix class name for arena prize.

- kod/object/active/holder/nomoveon/battler.kod
- kod/object/active/holder/nomoveon/battler/monster.kod
- kod/object/active/holder/nomoveon/battler/player.kod
- kod/object/active/holder/nomoveon/battler/player/user.kod
- kod/object/active/holder/room/monsroom/survivalroom.kod
- kod/object/passive/spell/utility/phase.kod
- kod/util/survivalmaint.kod
* Allow phasing back in while phased
> Survival Tweaks

- kod/object/active/holder/room/monsroom/survivalroom.kod
- kod/util/survivalmaint.kod
Fixing a few remaining issues with survival arena.
> Survival Arena fixes.

- kod/object/active/holder/nomoveon/battler/monster/lupking.kod
Stop Lupogg King casting hold on players he can't see.
> Add LoS check to Lupogg King hold.

- clientd3d/client.h
- clientd3d/map.c
- include/proto.h
- kod/include/blakston.khd
- kod/object/active/holder/nomoveon/battler/player/user.kod
- kod/object/active/holder/room/monsroom/survivalroom.kod
Bosses will have a large red dot with dark red halo, minibosses a slightly smaller red dot with purple halo.
> Add minimap dots for Survival Arena bosses.

- kod/object/active/holder/nomoveon/battler/monster/troop.kod
- kod/object/active/holder/nomoveon/battler/player.kod
Was checking PFLAG2_TEMPSAFE in piFlags instead of piFlags2.
Troops need to set their attack range from the weapon after creation,
instead of using viAttackRange.
> Fix gh flag bug, troop attack range bug.

- blakcomp/blakcomp.vcxproj
- blakcomp/blakcomp.vcxproj.filters
I think this still needs some work done to it, but it successfully builds the debug version of bc.exe, and builds release with some warnings.
> Add blakcomp VS project.

- blakserv/sprocket.c
- clientd3d/client.def
- clientd3d/list.c
- clientd3d/list.h
- clientd3d/protocol.c
- clientd3d/protocol.h
- include/proto.h
- kod/include/protocol.khd
- kod/object/active/holder/nomoveon/battler/player/user.kod
- module/merintr/inventry.c
Client can now drag and drop items within the inventory, and items will stay in their new positions. Sends a request to the server to update the plPassive list for the player.
> Add ability for client to move items around in inventory (inventory sorting).

- README.md
Removed some of the steps that are done automatically, added VS solution.
> Update readme.md to reflect new build process.

- kod/object/active/holder/nomoveon/battler/monster/towns/crnthtwn/cnsarge.kod
- kod/object/active/holder/nomoveon/battler/monster/towns/hazartwn/hzelder.kod
- kod/object/active/holder/nomoveon/battler/monster/towns/jasprtwn/jselder.kod
- kod/object/active/holder/nomoveon/battler/monster/towns/marntwn/MrElder.kod
Some added features were blocking Rook and the town elders from accepting signet rings.
In fixing this I've changed the GotWantedItem calls to CheckWhyWanted, both are equally valid but CheckWhyWanted seems to be the ideal implementation here, in the unlikely case that GotWantedItem is ever modified.
> Fix some NPCs not accepting signet rings.

- kod/object/active/holder/nomoveon/battler/player/user.kod
- kod/util/system.kod
Last login time not getting set before user tries to log in with their
new character - the blocking code for illegal character logins was
preventing new valid characters.
> Fix char creation issue.

- kod/object/active/holder/nomoveon/battler/monster.kod
- kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod
- kod/object/active/holder/nomoveon/battler/monster/reflectn.kod
- kod/object/active/holder/nomoveon/battler/player/user.kod
They weren't using the correct attack range in several places (my fault from excessive optimisation).
> Fix reflections/ETs not using bow from correct range.

- kod/object/item/passitem/weapon.kod
- kod/object/item/passitem/weapon/axe.kod
- kod/object/item/passitem/weapon/bkdagger.kod
- kod/object/item/passitem/weapon/goldswrd.kod
- kod/object/item/passitem/weapon/huntsw.kod
- kod/object/item/passitem/weapon/longswrd.kod
- kod/object/item/passitem/weapon/mystswrd.kod
- kod/object/item/passitem/weapon/neruswd.kod
- kod/object/item/passitem/weapon/ranged.kod
- kod/object/item/passitem/weapon/ranged/bow.kod
- kod/object/item/passitem/weapon/ranged/bow/battlbow.kod
- kod/object/item/passitem/weapon/ranged/bow/magicbow.kod
- kod/object/item/passitem/weapon/ranged/bow/nerubow.kod
- kod/object/item/passitem/weapon/ranged/bow/pracbow.kod
- kod/object/item/passitem/weapon/riijaswd.kod
- kod/object/item/passitem/weapon/testswrd.kod
This is a much easier and faster way to adjust weapon range without
effecting all the weapons.
Instead of using weapon quality values this uses the common viRange = $
> The old way to determine weapon range was not very good

- blakserv/adminfn.c
Some messages (e.g. garbage collecting messages when reloading system)
take a long time to run thus will set the highest timed blakod message
to a value greater than any message called during normal operation.
Added a "reset" menu to the server text commands, containing a single
option "highest". Using the command "reset highest", an admin can print
out and reset the value for the highest called message.
> Add admin command to reset highest timed message.

- kod/object/passive/questtemplate/mysterymobqt.kod
- kod/object/passive/questtemplate/priestessinsigniaqt.kod
Parrin added as a NPC for the shield insignia quest.
> Allow Parrin to add Jala insignias to shields.

- kod/object/active/holder/nomoveon/battler/player.kod
- kod/object/passive/spell/radiusench/jala.kod
- kod/object/passive/spell/radiusench/jala/hinder.kod
- kod/object/passive/spell/radiusench/jala/hinder/civility.kod
- kod/object/passive/spell/radiusench/jala/hinder/concil.kod
- kod/object/passive/spell/radiusench/jala/hinder/disharm.kod
- kod/object/passive/spell/radiusench/jala/hinder/profnres.kod
- kod/object/passive/spell/radiusench/jala/hinder/sacrdres.kod
- kod/object/passive/spell/radiusench/jala/hinder/truth.kod
- kod/object/passive/spell/radiusench/jala/invigor.kod
- kod/object/passive/spell/radiusench/jala/jig.kod
- kod/object/passive/spell/radiusench/jala/manaconv.kod
- kod/object/passive/spell/radiusench/jala/melcholy.kod
- kod/object/passive/spell/radiusench/jala/mirth.kod
- kod/object/passive/spell/radiusench/jala/rejuven.kod
- kod/object/passive/spell/radiusench/jala/restorat.kod
- kod/object/passive/spell/radiusench/jala/spelbane.kod
- kod/object/passive/spell/radiusench/jala/warptime.kod
First off, this fixes spell power not stacking from multiple instruments, (lute + necklace)
Second, I have increased all of Jala's range to a base of 12, at 99 spell power your range will be 20
(little more than a battle bow)
Third and least important, fixed all the space errors in the Jala spells
> Changes to Jala song range, allow stacking of spell power from instruments.

- kod/object/active/holder/nomoveon/battler/monster.kod
- kod/object/active/holder/room.kod
Few minor changes to speed up a few messages that get called frequently
and make unnecessary checks that can be prevented. Cleaned up some
spacing also.
> Small performance related changes to code in room/monster.

- blakserv/adminfn.c
Otherwise IPv4 addresses sometimes will not fit.
> Increase IP field size in admin who command.

- blakcomp/function.c
- blakdeco/blakdeco.c
- blakserv/adminfn.c
- blakserv/blakserv.h
- blakserv/ccode.c
- blakserv/ccode.h
- blakserv/loadall.c
- blakserv/loadall.h
- blakserv/sendmsg.c
- blakserv/session.c
- blakserv/session.h
- blakserv/timer.c
- include/bkod.h
- kod/util/system.kod
Added C_SaveGame and C_LoadGame C functions. SaveGame takes no
parameters and returns a blakod string containing the save game time.
LoadGame takes a blakod string as a parameter, and loads the int value
contained in the string, if valid.
Added these functions to StartChaosNight and EndChaosNight to allow
automating frenzy using the RealTime system.
> Automate saving/loading game for Frenzy.

- kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcbonepr.kod
- kod/object/active/holder/nomoveon/battler/monster/towns/marntwn/MrElder.kod
Now player wont have to run back to the main land to reset there stats
if the find a trinket while building on island and want to restat for
whatever reason
> made the bone priestess except trinkets for stat reset

- kod/object/active/holder/nomoveon/battler/monster.kod
- kod/object/active/holder/nomoveon/battler/monster/BRAMBLE.kod
- kod/object/active/holder/nomoveon/battler/monster/lvstatue.kod
- kod/object/active/holder/nomoveon/battler/monster/lvstatue.lkod
Statues will now regen lost body parts as they heal from damage. The
description will also list what HP the statue can take the player to.
> Make statues regenerate body parts when healing, fix desc.

- kod-udl.xml
> Update KOD syntax highlighter, move to top level

- run/server/blakserv.cfg
> Add (default disabled) MySQL section to blakserv.cfg so people know the

- kod/object/active/holder/nomoveon/battler/monster.kod
individually specified classes
> Change IsObjectX messages to use the ITEMTYPE_ bitfield rather than

- clientd3d/audio.c
> Fix nmake build due to warning treated as error in audio.c

- kod/object/active/holder/room/monsroom/objroom/castle1.kod
Was causing the server to lock up by posting thousands of messages.
> Remove incorrect call from castle1.kod

- kod/include/blakston.khd
- kod/object/active/holder/nomoveon/battler/monster/xeochctl.kod
- kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeoair.kod
- kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeoearth.kod
- kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeofire.kod
- kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeowater.kod
- kod/object/passive/trestype/makefile
- kod/object/passive/trestype/xeoairt.kod
- kod/object/passive/trestype/xeoeartht.kod
- kod/object/passive/trestype/xeofiret.kod
- kod/object/passive/trestype/xeowatert.kod
- kod/util/system.kod
this is so we can have node attacks without heart stones
> Added Xeo treasure types

- kod/object/active/holder/room/ghall/guildh5.kod
- kod/object/active/holder/room/monsroom/f8.kod
Added a closing mechanism for Konima's GH chest door, which will close the door after a minute.
Fixed up some incorrect coords for Lake of Jala's Song guild hall balcony.
> Add close mechanism for Konima's GH chest.

- kod/object/active/holder/nomoveon/battler/player/user/dm.kod
- kod/object/active/holder/room.kod
DMs can turn off PK for an hour in a given room by saying "turn off pk".
> Hour No PK DM say command

- kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeoill.kod
- kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeounholy.kod
invis to unholy xeo and reflections to riija xeo
> Xeo upgrades

- kod/object/active/flag.kod
Lowers the faction flags to half-staff for various reasons chosen by server admins.
This pull request in memory of the lives lost in Paris, France in November 2015, may we honor them properly in the future.
> Add message HalfStaff to class Flagpole

- kod/object/item/passitem/numbitem/food/inkycap.kod
- kod/object/item/passitem/numbitem/reagent/bdrgscal.kod
- kod/object/item/passitem/numbitem/reagent/firesand.kod
- kod/object/item/passitem/numbitem/reagent/solagh.kod
- kod/object/item/passitem/numbitem/reagent/uncserpm.kod
- kod/object/item/passitem/numbitem/reagent/yrxlsap.kod
inkies
bds
fire sand
solagh
uncuts
yrxlsap
> lower the wieght of these regs

- blakserv/config.c
Timeout on char select/char create increased from 10 minutes to 60 minutes.
> Increase select char/char creation timeout period.

- blakserv/async.c
- blakserv/builtin.c
- blakserv/config.c
- blakserv/game.c
- blakserv/list.c
- blakserv/synched.c
Fixed some issues suggested by VS's code analysis. The memset issue in synched.c was also recently fixed in the upstream repo.
> Fix compiler suggested issues.
