OpenMeridian/Meridian59

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/revenant.kod
Added the other state transitions that modify a target's piMonsterChasers. Revenants do not add to this, so they shouldn't subtract from it. Included TargetSwitch here also.
=> Override EnterStateLimbo for revenants to prevent constant lowering of a player's piMonsterChasers. Stop target switching to offline players.

kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod, kod/object/active/holder/nomoveon/battler/monster/reflectn.kod
On rare instances, someone looking at a reflection or evil twin while it
is in the process of being deleted will cause errors to be thrown as it
tries to send messages to $. This can occur with other messages that
call ToCliObject in user.kod. The removal of poOriginal will now be
posted, so any calls that require this data will still succeed while in
the process of deletion.
=> Post setting of poOriginal to $ to avoid errors with reflections and evil twins.

clientd3d/d3ddriver.c
This reverts https://github.com/Daenks/Meridian59_103/commit/e651a2c9fc4bf349962295aaabd26ce32224de99 , which enabled D3DPOOL_MANAGED.
There is 1 verified error report of a fully black-screen after login which is caused by this change.
And another one in the 103 globes which is very likely connected to this change.
=> Deactivate D3DPOOL_MANAGED again (due to few incompatible GPU)

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod, kod/object/active/holder/nomoveon/battler/monster/reflectn.kod, kod/object/active/holder/nomoveon/battler/monster/revenant.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod
Catching remaining ET deletion errors, set revenant ptPlace timer
to $ in Place, dispel ETs if the original logs off in another room
and make players killed by ETs from monsters display the correct
name for the killer.
Refactor SetMaster to handle the special ET case by having a SetMaster in
eviltwin.kod. Added a behavior flag check (for AI_MOVE_FOLLOW_MASTER) in
SomethingLeft so minions don't follow if they aren't supposed to (i.e. ET).
=> Another ET deletion fix, rev timer property fix. SetMaster refactor.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod
Previous fix stopped minions from following if they were fighting
something. Also, they'll now correctly lose the AI_FOLLOW flag once they
are set free.
=> Fix minions not following, remove AI flag on loss of master.

kod/object/active/holder/nomoveon/battler/monster.kod
Mobs will now show "This monster will take you to x hitpoints." under the description, where x is the monster's viLevel (the max HP a player can get from it).
Implemented it via temp string so we can change the message shown to players without forcing another resource download.
=> Add max possible HP that can be obtained from a monster to its description.

kod/object/active/holder/nomoveon/battler/monster/troop.kod
Currently a Soldier will hit you once to your 3 hits. Because of this I can kill them with a thirty hit point character with acid touch.
This should make then hit 1 for 1, making them very dangerous for characters under sixty hit points
=> Speed up soldier's attack to make them a better fight

clientd3d/project.c, clientd3d/project.h, clientd3d/server.c, kod/object/active/holder/nomoveon/battler/player/user.kod
Rather than sending n BP_RADIUS_SHOOT packets, send one and let the client allocate n projectiles in RadiusProjectileAdd. Shifts the processing to the client (instead of the server sending the same info for however many projectiles need to be sent), and removes issues drawing large number of projectiles (due to each one requiring a separate BP_RADIUS_SHOOT message).
=> Radius projectile angles now calculated by client, and only one BP_RADIUS_SHOOT message sent for each radius proj spell cast.

kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod, kod/object/active/holder/nomoveon/battler/monster/reflectn.kod
Add a setting for the % of original damage a reflection or ET can do. Default here is 50% (damage halved) though players are suggesting ET start off at 100%.
=> Halve flec/ET damage, implement dmg % as setting.

makefile
Keen's new version of keybind compiles on the buildserver and works on 104. Adding keybind back to makefile so we can compile keybind automatically.
=> Re-add keybind to makefile to build new keybind.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/passive/spell/persench.kod, kod/util/qormas.kod
Buffs cast from potions were being added to the player's passive improvement list. This check prevents that from happening (spell items already send bItemCast to CastSpell, it just wasn't being passed to StartEnchantment).
=> Don't add item-cast spells to passive improvement list.

keybind/m59BindForm.cs
Shift, Ctrl, and Alt were not being accepted as valid keybinds when used alone.
=> Fix modifier bug in keybind

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/player/user.kod
The default from viObject_flags is OF_ATTACKABLE, NPCs should be removing this flag. This flag is now set in Battler.
=> Fix OF_ATTACKABLE flags for NPCs.

keybind/m59BindForm.cs
Added punctuation symbols to the Switch statement for assigning keys.
Also added backspace and escape as options, disallowed numbers (old
keybind didn't allow these, they don't seem to work either) and Function
keys (these are used in aliases.
Fixed a bug caused by the Look Up field setting the Backward field.
=> Allow punctuation, disallow numbers and function keys in Keybind.

kod/util.kod
The two-color XLAT messages in Util weren't set up to handle two-color translations using a single XLAT. Modified them so that items can easily take a translation of this type. Depending on the type of XLAT (skin translated or not) the Decode messages should return the XLAT itself for both primary and secondary colors (items will handle these) or return the XLAT for the primary, and the skin color translation for the secondary (used for correctly matching skin tones on clothes).
=> Allow new XLATs to translate clothes correctly.

kod/object/active/holder/nomoveon/battler/player.kod
This shouldn't be taking spells that can't be forgotten (e.g. Blink, Phase etc).
=> Don't take utility spells in StripSpellsOfSchool.

kod/object/item/passitem/defmod/shield/guilshld.kod
Herald shields will now display the correct color in the description if translated with the new XLATs.
The Randomize message in guilshld.kod now has a 10% chance to pick one of the new/unused color translations. This applies to herald shields found in CV crate, but not to herald shields in the Guild shield menu. This makes the new colors suitably rare, along with assuming that out of the 13 new color choices, not all are equally desirable.
New herald shield color choices are: dark green, dark grey or black paired with one of three skin tones, red or blue paired with black, and black paired with white (two translations for this, will flip where each color is on the shield).
=> Add resources for new herald shield colors., allow new colored heralds to spawn randomly (but not available in guild shield menu).

kod/object/active/holder/nomoveon/battler/player/user.kod
Players previously could not see their carried bulk.  It was possible for the user to have a full inventory due to max bulk when their weight carrying capacity had not been exceeded.
=> Add stat bar for bulk

kod/object/passive/trestype.kod
Added the stat reset token to the treasure generation system. They drop with 0.033% to 0.1% chance depending on monster level (scales from level 50 to level 150). Players must be below the level of the mob they're fighting to get the token, to encourage building versus killing the weakest mob they can find for tokens.
Formatted trestype.kod.
=> Add stat reset tokens to loot table.

kod/object/active/holder/nomoveon/battler/monster/nrthlwrm.kod
Vigor drain caused by narthyl worm hits was far too high with safe spots removed and the possibility of multiple aggro. Lowered the vigor loss min bound from 3 to 0, and the max from 7 to 3. In testing vigor still noticeably drops, but no longer requires the player to rest or be constantly too full to eat.
=> Lower vigor drain from narthyl worms.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/passive/skill.kod, kod/object/passive/skill/secwind.kod, kod/object/passive/spell/crysmana.kod, kod/object/passive/spell/utility/phase.kod
Second Wind and Crystalize Mana will now show the time until the effect
wears off if the player clicks on the icon in their enchantment bar.
Clicking on the Phase icon will also tell the player how long they can
remain phased before taking penalties, and clicking on the spell
description will let them know how long they can phase for.
=> Add timers in descriptions for Second Wind, Cryst Mana and Phase.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/dethspid.kod, kod/object/active/holder/nomoveon/battler/monster/duskrat.kod, kod/object/active/holder/nomoveon/battler/monster/evilent.kod, kod/object/active/holder/nomoveon/battler/monster/scorpion.kod, kod/object/active/holder/nomoveon/battler/monster/skel/daemskel.kod, kod/object/active/holder/nomoveon/battler/monster/spdrquen.kod, kod/object/active/holder/nomoveon/battler/monster/spider.kod, kod/object/active/holder/nomoveon/battler/monster/thrasher.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/passive/spell/SUMMTWIN.KOD, kod/object/passive/spell/apparitn.kod, kod/object/passive/spell/sweep.kod, kod/util/system.kod
Casting ET on a monster generates a copy of that monster, not a true
evil twin. This fix will allow kills made by those copies to count
correctly as kills by the master, if the victim is another monster with
no master (or a monster master).
Add hit side effect messages for ill form/morphed players.
Will give a success message to the attacker when a hit side effect is
performed on a victim (e.g. dusk rat poison, daemon skel enfeeble).
=> Handle monster ET kills correctly; give attackers a success message when illusioned as a monster and performing a hit side effect such as poison.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/passive/trestype.kod, kod/util/statistics.kod
Occasionally a player can attack a monster that is already dead (due to
latency) and it results in calling SquaredFineDistanceTo3D on a monster
that has bad coordinates. This should fix that by moving the same room
check before getting range in Player.
Added a debug message in when an ancient trinket is found, to see how frequently they are dropping. Also added a property to the Statistics object to keep track of the number.
Added more info to the debug message given when a user changes their stats (the old and new stats are now logged).
=> Fix calling SquaredFineDistanceTo3D on dead monsters. Add tracking mechanism for ancient trinket drops.

kod/object/active/wallelem/asburstc.kod, kod/object/active/wallelem/poisfogc.kod, kod/object/active/wallelem/wallfire.kod, kod/object/active/wallelem/wallltng.kod, kod/object/active/wallelem/web.kod
Wall elements have long been a way for players to attack monsters
without the monster doing anything. The correct code is now called when
a player attacks a monster using a wall element.
Also added golems to the list of monster unaffected by spider web
(they're huge and heavy, no way would they be stuck here).
=> Fix wall elements not causing monsters to aggro.

kod/object/active/holder/nomoveon/battler.kod, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/passive/spell/animate.kod, kod/object/passive/spell/debuff/seduce.kod, kod/object/passive/spell/summrefl.kod, kod/util/settings.kod
Moved bulk of the minion control code from Player to Battler. Player and
Monster both have their own version of CommandMinionAttack due to the
extra checks needed for players. Minions for monsters function the same
as they do for players and recursion is also allowed - players can
theoretically have minions that have minions themselves.
Seduce and Animate have been modified so that monsters can also cast
them if necessary. If a monster casts Seduce, it is allowed to charm the
target.
=> Allow monsters to have minions. Convert Seduce and Animate for use by monsters.

kod/object/active/holder/nomoveon/battler/monster/lupking.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/room/monsroom/survivalroom.kod, kod/object/passive/spell/atakspel/earthqua.kod
Wrap MsgSendUser in AllowPlayerAttack with a report check to prevent sending this when APA is used for determining attackability (i.e. minimap dots).
Add sanity checks to EQ and lupogg king to prevent errors.
=> Spectator/phase crash fixes; eq/pogg king error fixes.

kod/object/active/holder/nomoveon/battler/monster/lupking.kod, kod/util/settings.kod
Lowered pogg king hold time from 30-45 sec to 15-25 sec. Added class
variables for hold time so we can modify them in-game easily.
Edited the default settings for free stats reset cap to 19HP (i.e. no
free stat resets) and ancient trinket drop rate to reflect the currently
used values on 103.
=> Lower lupogg king hold time. Update stats reset settings.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/BRAMBLE.kod, kod/object/active/holder/nomoveon/battler/monster/thrasher.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/room/monsroom/survivalroom.kod, kod/object/passive/spell.kod, kod/object/passive/spell/atakspel.kod, kod/object/passive/spell/atakspel/earthqua.kod, kod/object/passive/spell/atakspel/radproj.kod, kod/object/passive/spell/roomench/heat.kod, kod/util.kod, kod/util/statistics.kod, kod/util/survivalmaint.kod, kod/util/system.kod
-Fixed Bramble Wall starting hit points (were being spawned with 0HP).
-Fixed Bramble Wall damage threshold messages.
-Stop thrasher spin attacks hitting phased/spectating players.
-Fix a bug causing thrasher spin attacks to overwrite the damage to be
done to each target with the value returned from the previous target.
-Changed thrasher spin attacks to use high precision damage numbers.
-Survival arena now checks for invalid targets before calling
TargetSwitch.
-Added IsOwnedByPlayer message in Monster. Returns TRUE if the monster
(or its master) is owned by a player, FALSE otherwise. Checks for
apparitions and monster evil twins in addition to true minions.
-Added minion checks to the aggro code in survival arenas, to stop
player minions being aggroed on players.
-Fixed bug causing new …
=> Misc bug fixes, Solo Survival Arena aggro adjustment.

kod/object/active/holder/nomoveon/battler.kod, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod, kod/object/active/holder/nomoveon/battler/monster/nrthlwrm.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room/monsroom.kod, kod/object/active/holder/room/monsroom/survivalroom.kod, kod/object/passive/spell/SUMMTWIN.KOD, kod/util/survivalmaint.kod
-Changed the Posting of TargetSwitch and EnterStateChase to Send in 
AggroSome/AggroOne - the monster is present on-screen already so 
Post isn't necessary.
-Add a loop to GenerateMonster in MonsterRoom which will attempt up to
15 times to spawn a monster in a random location if no plGenerators list
is present. Allows spawning of mobs in rooms with no plGenerators and a
lot of space where mobs can't move.
-Add IsMinion message to Monster to allow easier checking for minions
(both player and monster owned).
-Add resource restoration after each round is completed in survival
arena.
-Add properties for resource restoration and and last join level to
SurvivalRoomMaintenance so they can be modified for all survival arenas
created.
-Cleaned up some code and simplified some checks in …
=> Survival arena bug fixes/code improvement, add resource restoration on level completion, bug fixes for ET deletion.

kod/object/active/holder/nomoveon/battler/monster/elemental.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/eaeleme.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/eaeleme/eaelech.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/fieleme.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/fieleme/fielech.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/iceleme.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/iceleme/icelech.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/neeleme.kod, kod/object/active/holder/nomoveon/battler/monster/elemental/neeleme/neelech.kod
Adjusted elemental resistances, fixed Constructed issue with overwriting resistances, raised champions from level 230 to 250 and difficulty 8 to 9. Raised normal elementals from difficulty 7 to 8.
To address the individual resistances:
Earth Champion and Earth Elemental have 50% resist to all spells and all weapons. Weak to acid by 70%. Weak to cold and fire by 25%. Weak to bludgeon by 50%.
Nerudite Champion has 50% resist to all spells and all weapons. Has 60% weakness to quake, and 60% weakness to pierce.
Nerudite Elemental has 50% resist to all spells and all weapons. Has 70% weakness to quake, 60% weakness to pierce, and 20% weakness to holy and unholy.
Fire Champion has 90% resist to all spells, 60% to all weapons. Has 80% weakness to cold, and 50% weakness to thrust.
Fire Elemental …
=> Elemental resist/hp adjustment.

kod/include/blakston.khd, kod/object/active/holder/nomoveon/battler/player.kod
Forgot to add a check for the victim actually dying by another player.
Added a new PFLAG, PFLAG_KILLED_BY_PLAYER which is set if the killer is
a player. Flag is removed when penalties are applied, at which time a
boolean is set to activate the temp angel.
=> Fix for players getting the temp safe angel without being killed by a player.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/item/passitem/KarmaPotion.kod, kod/object/item/passitem/warjoin.kod, kod/util/chaosnight.kod, kod/util/system.kod, kod/util/warevent.kod
During a frenzy war event, all players will now be drawn with red halos or if allied, green halos. Added an IsSameSide message to WarEvent to facilitate this.
Added a boolean property to WarEvent to allow or disallow attacking of teammates (default no attack).
Formatted warevent.kod.
Added frenzy loot to innkeeper NPCs - loot no longer distributed through globalgive. These can be reversed via booleans in the frenzy object. The default settings will hand out 200000 shillings to players every 3 minutes, allowing them to buy their own loot in the remaining safe zones.
But, how will they carry all those items? Frenzies will now use the new SetClassVar C function (requires #933) to reduce the bulk and weight of all items to 1. Combined, these two changes will enable inventory organisation …
=> War event formatting and improvements.

kod/object/active/holder/room.kod, kod/object/active/holder/room/monsroom/objroom/castle1.kod
So they can get revenge on players botting Final Rites and Earthquake. If the skeleton tries to move onto the door location, they use the door.
=> Allow skeletons to use doors in CV main room.

clientd3d/client.h, clientd3d/move.c, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room/monsroom/survivalroom.kod, kod/object/passive/spell/SUMMTWIN.KOD, kod/util/survivalmaint.kod
Fix an error in the TP calculation for survival arenas - should divide rather than multiply by the survival TP increase level.
Added a target $ check to CastSpell in SummonEvilTwin, rarely a monster will try to cast this with $ target.
=> TP fix, monsters casting ET fix.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room/monsroom/survivalroom.kod
-Set poLastAttacker to $ on monster deletion.
-Increase MAX_LOGGED_THRESHOLD for piCheaterLogs to 50 (up from 25).
Increment piCheaterLogs for transmitted speed changes.
-More checks for $ list/object in SurvivalRoom; sometimes the
plParticipants list is $ and this causes some errors.
=> Minor error fixes.

kod/object/active/holder/nomoveon/battler/monster/lupking.kod, kod/object/active/holder/nomoveon/battler/monster/orcboss.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/passive/guild.kod, kod/object/passive/spell/walspell/brmblwll.kod, kod/object/passive/spell/walspell/summfog.kod, kod/object/passive/spell/walspell/summpfog.kod, kod/object/passive/spell/walspell/summweb.kod
This code gets the player's row/col to determine where to place the elements, but the if statements neglect to account for the player facing exactly ANGLE_ENE. Some of the wall spells had the correct logic here, these ones didn't. If a player happened to be standing at ANGLE_ENE and cast the spell, the elements weren't placed and a lot of errors logged instead.
Fixes also included here are prevention of survival arena start/join from Fields, a fix to pogg king (clear the plAttackers list on deletion) to stop GetObjectByID errors in survival arena, and fixes for deleting non-existent timers in OPB and guild deletion.
=> Fix error in placing wall elements due to bad handling of player angle, misc. bug fixes.

clientd3d/client.h, clientd3d/key.h, module/merintr/merintr.c
Player requested - there was no target self key available for classic key binding, so I've enabled the \ key to do this. Also defined VK_BACKSLASH in key.h and added it to the ascii key map in merintr.c.
=> Add target self key for classic key binding.

kod/object/active/holder/nomoveon/battler/monster/grdworm.kod, kod/object/active/holder/nomoveon/battler/monster/revenant.kod, kod/object/active/holder/nomoveon/battler/monster/towns/Goad.kod, kod/object/active/holder/room/barlqrm/barapoth.kod, kod/object/active/holder/room/necarena.kod, kod/object/passive/spell.kod, kod/object/passive/spell/heal.kod, kod/object/passive/spell/hospice.kod, kod/object/passive/spell/majheal.kod
Fix up timer errors with revenants and groundworms - both of these are generating rare errors for still existing timers for deleted monsters.
Fixed a bug with Goad's Arena which was occasionally preventing players from being teleported to the arena correctly.
=> Timer error fixes, Goad's Arena teleport bug fix.

kod/object/active/holder/nomoveon.kod, kod/object/active/holder/nomoveon/battler.kod, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/troop.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room/crnthrm/corinn.kod, kod/object/active/holder/room/tosrm/tos.kod, kod/object/item/passitem/easteregg.kod, kod/object/item/passitem/numbitem/food/chaosfood.kod, kod/object/item/passitem/weapon/bkdagger.kod, kod/object/item/passitem/weapon/unique.kod, kod/util/assgame.kod
Thrust resist should be 15, not 16. Bludgeon is displayed twice if this happens.
Removed a brazier that was behind a wall in CN inn.
Added IsBeverage message to EasterEgg class, called when someone tries to eat the egg but is full.
Cleaned up the IsInSameRoom message in NoMoveOn; message is much faster without all the unnecessary Send calls.
Fixed faction soldier NPCs doing slash damage no matter what weapon they are holding. They now ask the weapon for what damage type to do.
Fixed mana not regenerating after phasing back in. The mana timer is stopped if a user is phased out but is not started when phased back in. The timer will now be active during phase, but no mana will be lost or gained (it now works same as the health timer).
Fixed Assassin's game maintenance timer not being deleted …
=> Fix wrong user stat resistance being displayed, remove brazier from behind wall in CN inn. Misc. other bug fixes.

blakserv/ccode.c, blakserv/term.c
This is intended to be complementary to Keen's real-time/game event pull request. One of the issues faced with that system was the inability to call a message at a set time in the future without messy timer interactions (multiple timers for longer than 37 hours).
This pull request will allow C_SendMessage and C_PostMessage to be passed a string (TAG_STRING only) instead of a proper message, from which both C calls will use the message name given to obtain the proper message ID. This is handled inside the check for != TAG_MESSAGE thus existing calls should not run any slower.
C_SetString can now create its own string if passed $ to avoid the need for two calls to create a string. It can also now handle TAG_DEBUGSTR (anything enclosed in " ") and TAG_MESSAGE. If C_SetString is passed a …
=> Allow KOD message names to be easily saved as strings by SetString. Add support for calling messages by string to SendMessage and PostMessage.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/passive/spell/dmspell/damn.kod, kod/object/passive/spell/dmspell/dmrescue.kod
There are several issues with having only a single honor string for players (and numerous bugs in the current psHonor system). Players now have a plHonor list which can contain several strings, all of which are appended to the player's bio. psHonor has to be left in until players can have their psHonor string added to the plHonor list via admin command (SetHonorStrings message, which ignores broken psHonor strings).
=> Convert single honor string in Player (psHonor) to honor string list.

clientd3d/client.h, clientd3d/intrface.h, clientd3d/key.c, clientd3d/key.h, clientd3d/statgame.c, clientd3d/winmsg.c, keybind/m59BindForm.cs
This change causes mouselook toggle and tab keys to be treated as repeat actions, so both can be repeated instantly. It also stops the idle keyboard polling from performing either of those actions, the net result being that mouselook/tab window can always be toggled, but will not toggle repeatedly if the key is held down. Client min version incremented.
NOTE: only applies to main graphics window, so holding down tab on stats/inventory list or chat box will always bring focus back to graphics window.
=> Stop mouselook and tab repeat toggle on key held down. Increment client min version to 26.

kod/object/active/holder/nomoveon/battler/monster/skel/daemskel.kod
Due to the large amount of complaints from players regarding daemon skeleton on-hit effects, have removed enfeeble entirely from being cast by them, and lowered the effectiveness/duration/chance of dement casts. Dement will cast 5% of the time (down from 10%), at 15 spellpower (down from 50).
=> Remove enfeeble from daemon skeletons, lower dement chance/spellpower.

kod/include/blakston.khd, kod/object/active/holder/room.kod, kod/util/settings.kod
When we introduced the high resolution grid, we also made small modifications to the LOS code.
Right now LOS is granted even in case the last step on the LOS line fails (SKIP=1). Additionally to the higher resolution grid already getting rid of many safe-spots and allowing monsters to step through tiny mazes, this small additionally change made sure there are absolutelty no safe-spots anymore. However it also tends to make creatures hit through zero-thickness walls like half-transparent fences for example.
This change here now brings some flexibility. It turns the static code skipping the last step into a configuration value in settings.kod (I replaced the deprecated LOS settings there, which are not in use anymore). By default this piLOSSkip in settings.kod should be LOS_SKIP_1 …
=> Config option (settings.kod) for LoS skip handling (safespots?)

clientd3d/d3drender.c
This code block was causing sky texture to be drawn between some texture junctions. Turning it off doesn't seem to actually break anything else, but fixes the errant sky drawing.
Edit: this causes a few extra lines in Marion (which already seems poorly rendered) however it fixes lines elsewhere (e.g. this one Diggie found: https://i.imgur.com/kTi7KOV.jpg).
=> Disable part of the wireframe hack in HW renderer.

kod/util/gameeventengine.kod
Compiler thinks there are duplicate parameters in ScheduleEventInMinutes if NewYear precedes it. Rearranging the NewX() messages fixes this (but is indicative of a serious issue in the compiler).
=> Rearrange messages to remove compiler error.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/ghost.kod, kod/object/active/holder/nomoveon/battler/monster/lich.kod, kod/object/active/holder/nomoveon/battler/monster/mummy.kod, kod/object/active/holder/nomoveon/battler/monster/skel.kod, kod/object/active/holder/nomoveon/battler/monster/specmum.kod, kod/object/active/holder/nomoveon/battler/monster/thrasher.kod, kod/object/active/holder/nomoveon/battler/monster/troop/necrotr.kod, kod/object/active/holder/nomoveon/battler/monster/zombie.kod
The @IsUndead message is called a lot for its relative importance (various calls to this in the top 50 calls) and as it returns a boolean that isn't changed, checking a classvar is quicker. Monsters could override this as a property if they needed to set it.
=> Add vbIsUndead boolean to monsters.

kod/object/item/passitem/spelitem/wand.kod, kod/object/passive/spell.kod
Discussed in IRC - currently the default behavior for using an item during attack cooldown is to have it fail with no extra info, and remove 1 from piHits. This change prevents wands from being used during the cooldown (without removing durability), but allows potions and scrolls.
Perhaps it isn't realistic to drink a potion or read a scroll during attack cooldown, but the presented argument was that it would open up some strategy with regard to fast item use (while still preventing
double attacks using lightning or other offensive wands).
=> Allow potion/scroll use during attack cooldown.

clientd3d/bsp.h, clientd3d/bspload.c, clientd3d/cache.c, clientd3d/client.h, clientd3d/client.rc, clientd3d/config.c, clientd3d/d3dcache.h, clientd3d/d3dparticle.c, clientd3d/d3dparticle.h, clientd3d/d3drender.c, clientd3d/d3drender.h, clientd3d/d3dtypes.h, clientd3d/draw3d.h, clientd3d/drawbsp.c, clientd3d/drawbsp.h, clientd3d/effect.c, clientd3d/graphics.c, clientd3d/maindlg.c, clientd3d/move.c, clientd3d/resource.h
Load room data as floats instead of integers, use in calculations for higher accuracy. I don't think there's much benefit to having the extra precision in software mode, but I have converted it for now anyway.
Fixes slope errors (gaps) and 99% of polygon cracks (i.e. wireframes).
The D3D header edits are to clean up compiler warnings (I'm not sure why they wrote the defines that way, I can't see a purpose to it as opposed to just defining).
Wireframe is on for now, as there are still a few stray sky pixels being drawn between polygons (interestingly, not on sloped surfaces).
Added FPS counter option to client preferences menu (English and German). Shows a text FPS ticker next to the lagbox. Code for FPS counter was already present, but not available outside of debug mode. FPS counter …
=> Client changes to load ROO v.14, graphics fixes, D3D refactoring.

clientd3d/move.c
Previous change to fix possible vigor exploits left players with under 10 vigor sometimes unable to change rooms, as it was being caught by the 'run with no vigor' code on the server.
Still not entirely happy with how this is all calculated on the server - it really should be calculating speed itself based on how the user is moving. Currently it forces the client to send a sane value if they wish to keep moving, but I think we could improve this.
@cyberjunk you'll probably need to change this in Ogre client too.
=> Fix players with < 10 vigor not being able to change rooms.

clientd3d/client.rc, clientd3d/download.c
The client will now attempt to run the patcher from the default location (..\Start Menu\Programs\OpenMeridian\) when updating and if that fails, it will attempt to download it from the homepage. If that fails, the user now gets a message to contact us at the forums.
=> Run patcher locally when updating before attempting to download it again.

kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod, kod/object/active/holder/room/monsroom/c4.kod
Mob was spawning just inside the wall, generator moved to the middle of path (players can still walk around it).
=> Fix spawn in wall in forest outside Marion.

clientd3d/client.h, clientd3d/drawbsp.c, kod/object/active/holder/nomoveon/battler/monster/lupking.kod
Some players are experiencing rare crashes with the upgraded client due to some calculations no longer being rounded to zero. This will fix those issues by replicating the rounding as before, and some checks have been added to prevent crashes if for some reason this still fails at some point (this is some of the older code in the client software renderer). Commented out a debug line that causes a lot of spam in the debug window (looking into it) and added a fix from the VS branch (variable initialisation).
Also added a fix for the lupogg king not-moving issue, where he gets stuck in a loop trying to cast hold on players he can't see.
=> Client crash fixes, lupogg king stuck-in-one-place fix.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/room/monsroom/marcryp1.kod, kod/object/passive/spell.kod, kod/object/passive/spell/atakspel/illwound.kod, kod/util/system.kod
RecreateAllSpells should be called in Recreate phase 3 but was commented out. CreateAllSpellsIfNew and CreateAllRoomsIfNew were added to Recreate phase 1 but new rooms are already handled in RecreateAllRooms, and spells (should be) handled in RecreateAllSpells.
Possible reasons for commenting out RecreateAllSpells:
- Dangling spell object references from WA_SPELLCASTER weapon attributes (see #1017)
- Ditto for Illusionary Wounds spell imitation list (fixed here).
- Ditto for Marion Crypt 1 Martyr's Battleground, which would cast when the room is recreated (but before the spells are, fixed here).
- Enchantments on players referencing the old spell objects, keeping them alive (fixed here).
- Statistics for spell casts are stored in the spell object, these will get cleared.
Reasons to run …
=> RecreateAll/object references changes.

blakcomp/actions.c, blakcomp/blakcomp.l, blakcomp/codegen.c, blakserv/kodbase.c, clientd3d/client.rc, clientd3d/d3drender.c, module/merintr/inventry.c
This is telling users to reinstall the whole client, when the error is just m59bind.exe missing or unable to be opened. Seems a little overkill (especially now that we have the patcher).
Fixed the inventory scrollbar not always drawing correctly.
Fixed view range issues on very large (future) screens. Currently the view limit is ~190 row/col units, this change raises it to ~380 (i.e. further than we'll likely ever need).
Added some small fixes from the original repo.
=> Rewrite missing m59bind.exe error message, fix inventory scrollbar drawing. Extend player viewing range.

kod/object/active/holder/nomoveon/battler/monster/lupking.kod
Check for valid Brain before sending PostAttackTimer, sometimes Lupogg King dies while he's going through all the cast spell/attack code.
Also fix up the bad logic in the CanSee override, and add the Jasper Sewers part of Lair that he can't see.
=> Check for valid Brain in Lupogg King PostAttackTimer, fix CanSee row/col checks.

kod/object/active/holder/nomoveon/battler/monster/specmum.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/util/settings.kod
Player requested. Change spectral mummy karma to 0, so players don't change karma when killing them. This is live already on 103, but this pull request will change the value in kod.
Forum thread: http://openmeridian.org/forums/index.php/topic,518.0.html
Added Taran's initial homeroom system setting from #721
=> Set spectral mummy karma to 0. Add system setting for initial homeroom (default RID_NEWB1).

kod/object/item/passitem/weapon.kod, kod/object/passive/itematt/weapatt/waspell.kod, kod/object/passive/spell/SUMMTWIN.KOD
Due to an 18 year old bug, the WA_SPELLCASTER weapon attribute was only ever making Mark of Dishonor weapons. When cycling through the choices, it never broke out of the loop when it picked a spell so it always ended up picking the last one on the list (MoD). It can now choose MoD, Vertigo, Enfeeble, Dement, Evil Twin or Forget.
Also changed the weapon attribute to use the SID rather than the spell object, as the object can be deleted/recreated (so the weapon ends up referring to the old spell object and keeping it active).
Added a message to weapon.kod to replace the spell object in all existing spellblades with the appropriate SID (FixSpellItemAtts). To fix all weapons, run the command "send c weapon FixSpellItemAtts".
Removed the swap spell from the spellblade spawn list (no current …
=> Fix WA_SPELLCASTER weapon attribute only spawning MoD on weapons. 

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcvaultm.kod, kod/object/passive/storage.kod
This smooths the withdrawal process for vaults. You can attempt to take out any number of things, but the vaultman will stop once you cannot carry anymore.
For example, if you take out a huge list of things, hit a plate armor, and can't carry it, no more will be withdrawn.
If you take out a huge stack of reagents, your tally will be reduced to exactly what you can carry.
I have also removed the 1 shilling fee per item withdrawn at the Ko'catan vaults. I am not entirely convinced it was even intentional. If it was... why? All it ever did was sometimes screw over people who had no shillings on them.
=> Partial Vault Withdrawal

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/room.kod, kod/util/settings.kod
Player requested: allow rolling toughers on group member kill, but halve default group time to compensate.
EDIT: changed this so that the defaults are the current live values (60 sec group time, FALSE for toughers on group kill).
=> Add settings for default group time and rolling for toughers on kill. Defaults are the current live values.

kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/nomoveon/battler/player/user/dm.kod, kod/object/active/holder/room/monsroom/g9.kod, kod/object/item/passitem/numbitem/reagent/elderbry.kod, kod/object/item/passitem/numbitem/reagent/emerald.kod, kod/object/item/passitem/numbitem/reagent/orctooth.kod, kod/object/item/passitem/numbitem/reagent/uncserpm.kod
Allows DMs to get rings, wands etc.
Most issues players are having with the Brax levers is due to the wait time needed before pulling the next lever. Lowered the time from 2 sec to 1 sec to reduce that issue.
A few reagents didn't have the proper indefinite article set, added it.
Fixed a FindHolding call in User that was sending the wrong parameter name.
=> Use item's true name with dm item command. Lower delay on Brax lever pulls. Add indefinite article "an" to a few items that were missing it.

kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/avchief.kod, kod/object/active/holder/nomoveon/battler/monster/lupking.kod, kod/object/active/holder/nomoveon/battler/monster/lvstatue.kod, kod/object/active/holder/nomoveon/battler/monster/troop.kod, kod/object/active/holder/nomoveon/battler/player.kod
This fix creates the dead body and monster loot exactly where the
monster was standing, instead of using the default value for that
finerow/finecol (32, 32) which sometimes placed the loot inside walls.
Players will also drop their loot exactly where they are standing
when killed.
The ReqSomethingMoved checks before item drops have all been removed -
if the player or monster can stand in that space, we will assume the
loot can be placed there also. The alternative is having loot rarely
still not drop if the player or monster is standing too close to
a wall.
=> Stop loot from players and monsters dropping inside walls when either dies.

kod/object/passive/itematt.kod, kod/object/passive/itematt/iabonded.kod, kod/object/passive/itematt/weapatt/waspell.kod
Added magic flag (colored name in lists) to spellblade and bonded items.
Also check when creating spellblade description that we have valid data
list. Artificed weapons don't actually have the data necessary to add
the spell to the description, so they throw an error here.
=> Add magic flag to spellblade and bonded items.

kod/object/active/holder.kod, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/item/passitem/numbitem.kod, kod/object/passive/storage.kod
Some bad logic was causing players to be able to carry over their maximum weight/bulk limit, and the bad return values from the weight/bulk calculations were causing errors in several places. Added
bounds and checks in Holder and NumberItem respectively to prevent this happening (redundant when called together, but that might not always be the case).
Removed an unnecessary debug message from VaultWithdraw in Monster that was being triggered by mundane behavior.
Added a check for valid number_list parameter before using it in Buy, as this was ending up $. I think it may be a client sending the wrong info here rather than anything in the server code (I know there is a player experimenting with a new type of bot that buys from NPCs).
Edit: The player has confirmed his bot was the cause of …
=> Fix vault and weight/bulk bugs.

kod/object/active/holder/room/duke2.kod
Put feast hall door on a timer.  DMs can still manually open and close the door.  If left open the system will close the door after a set period  Players in the foyer to the feast hall will be blinked out when the system closes the door.  Players inside the feast hall and ballroom will be moved to the main hall.
=> Put feast hall door on a timer.  DMs can still manually open and close

module/char/char.rc, module/char/charrc.h, module/char/charstat.c
Changed suggested stats to the following:
{ 40, 10, 50, 40, 10, 50 },  // Pure Fighter (Weaponcraft/Kraanan)
{ 40, 25, 50, 15, 35, 35},  // Shal'ille/Qor Warrior
{ 40, 35, 50, 25, 15, 35},  // Riija Warrior
{ 40, 50, 45, 15, 45, 5  },  // Pure mage
Did this a while ago, perhaps these are no longer valid. Opening this pull request so we can discuss it.
Edit: I don't really mind what we put here, anything would be an improvement on the current defaults.
Edit2: Added Gar's suggestions, and moved some PF might into agil. I've left the mights at 40 mainly because I think new players would be less frustrated with a higher weight limit, rather than trying to min/max their aim/agil.
=> Starting toon stat suggestion changes.

kod/object/active/holder/nomoveon/battler/player/user.kod, module/mailnews/newsread.c
Two static variables need to be reset when the news dialog is exited, otherwise the client will request the incorrect article number the next time a newsglobe or newsbook is opened.
=> Fix client trying to request incorrect news article.

blakserv/adminfn.c, blakserv/class.c, blakserv/interface.c
When reading resource parameters, the code was assuming that the
parameters were present without actually checking for them. This was
most noticeable with the "lock" command, which displayed garbage if no
lock text was given as it reads past the end of the "lock" string to
find the requested lock text.
Changed the 'R' parameter-based admin commands to use strtok correctly,
so the commands will now fail if the parameter is not present. This does
mean that lock will no longer work on its own, the alternative is to let
NULL through here but handle it correctly for every single
resource-based admin command (most of them cause blakserv to crash when
passed NULL).
Added a few safety checks, and increased the length of a buffer that
was causing blakserv to crash when viewing large debug messages …
=> Fix parameter handling for resource-based admin commands.

kod/include/blakston.khd
Currently players get kicked out of a faction after 24 hours of online
time, increased that to 48 hours. Lowered the minimum revisit time to 1
hour (from 4) and increased 'warn' time to 44 hours.
=> Increase loyalty time from 24hr to 48hr.

kod/object/active/holder/nomoveon/battler/player/user.kod, kod/util/settings.kod
This one might be a little controversial.
There have been several cases where users have suicided multiple built characters, and this is usually in a fit of rage that they later regret. Meridian characters can take hundreds of hours to build for less
experienced players, and I don't think we should allow it to be negated due to momentary anger. One of the high profile suiciders recently contacted me asking if we can restore his accounts, and I had to tell him that we could not.
In addition, this will prevent hacked/shared accounts from being suicided maliciously (this also happened recently).
Players who really need to suicide their characters can contact an admin, and we can do it for them. I've set the limit to 60HP - with the stat reset system, legit suicides over that amount should be …
=> Add maximum HP for player suicides.

blakserv/ccode.c, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/towns/barlqtwn/bqclerk.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room/barlqrm/barcourt.kod, kod/object/item/passitem/inscript.kod, kod/object/item/passitem/inscript/makefile, kod/object/item/passitem/inscript/namechscroll.kod, kod/util/settings.kod, kod/util/system.kod
Players can now go to Caramo and say "change name" or any variation
containing those two words, and she will give them a new "deed poll"
scroll on which they can write their new name.
If the name passes all the checks for creating a new character name, it
will be given to the player provided they can afford it. Money is taken
directly from player's bank account (no running around BQ with 3 mil).
Players receive a warning regarding the cost the first time they hand
back the scroll.
The name change code used on character creation has been moved to
separate messages in System for validating and creating user names. Name
change cost is a setting which can be changed live (default 3 mil).
The sign in Office of the Justicar has been updated with info regarding
the name change function. Name …
=> Add name change system to Caramo.

kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcapoth.kod, kod/object/active/holder/nomoveon/battler/monster/towns/tostwn/TsApoth.kod
To help players deal with cursed items away from Marion, the Tos and Ko'catan apothecaries will now sell Remove Curse potions.
=> Add remove curse potions to Frisconar and Zala.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/passive/questnode.kod
If a player fails a faction loyalty quest, DeadlineExpired is sent to all faction quests including the one that just failed. QuestNode handles this correctly and doesn't try to fail the quest twice, but the correct behavior here is to Post the rewards so that the failing quest is cleaned up (and removed from the player's quest list) before trying to clear all active faction quests for that player.
Fixed dodge/block/parry not improving due to some code being skipped in AdvancementCheck.
=> Handle cancelling faction quests correctly. Fix some skills not improving correctly.

kod/include/blakston.khd, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/nomoveon/battler/player/user/dm.kod, kod/object/passive/skill/secwind.kod, kod/object/passive/spell/multicst.kod, kod/object/passive/spell/radiusench.kod, kod/util.kod, kod/util/system.kod
The EVENT_SYSTEMSAVE trance break seems to cause more problems than it fixes via messages being called during garbage collect. Existing checks catch all but the rarest instance of incorrect object references during saves, so reverting this change.
Use pbLogged_On in player.kod rather than calling the message on self.
Use fine coords for placing items in dm.kod for more precision.
=> Revert system save trance breaking, fix up some message calls in Player/DM.

blakserv/config.c, blakserv/game.c, kod/object/active/holder/nomoveon/battler/player.kod
Added default values for prHead, prEyes, prMouth, prNose and prToupee
for when a new user object is created.
Players trying to bypass the character creation dialog on a new
character slot will now be prevented from entering the game, and blocked
from reconnecting from 60 seconds. Though the default values are now
fixed, this is undesired behavior hence the short block time.
Changed the default links for the ads in character select screen to Open
Meridian homepage and forums (still nothing displayed there).
=> Fix character select bugs, change charselect ad links.

kod/object/passive/spell/fdeath.kod
Spell is to useless to cost such an expensive reagent.
I'm requesting it be lowered.
=> Removing Solagh form feign death's reg cost

clientd3d/util.c
Disables the min/max checks vs. screen size that cause child windows to be placed on the primary monitor rather than the correct one, if meridian is on a non-primary monitor.
If you want to test this client, download here: https://drive.google.com/file/d/0B1S4dg5X_oh_UVJTcW1iVUM5LTQ/view?usp=sharing (current 103 release with this change).
=> Position windows correctly on multi-monitor setups.

keybind/m59bind.csproj
Will now copy the output exe to .\run\localclient.
=> Fix m59bind.exe not being copied by VS build.

kod/object/item/passitem/rod.kod, kod/object/item/passitem/rod/shieldrod.kod, kod/object/item/passitem/weapon/axe.kod, kod/object/item/passitem/weapon/shrtswrd.kod, kod/object/passive/spell.kod, kod/object/passive/spell/persench.kod, kod/object/passive/spell/roomench.kod
* EffectDesc needs to add a blank resource if the spell itself doesn't add
anything here, otherwise descriptions won't display correctly if they
don't have effect description additions.
* Axe and ss range values were swapped in the recent update, this changes them back.
* Add the 103-tested values for rod use delay (500ms, down from 1000ms) and shield rod duration (3s, down from 5s) to code to avoid having to set them each reload/recreate.
=> Fix some PE descriptions not showing up, fix axe/ss range, change rod values to 103-tested ones.

keybind/m59bind.csproj
$(SolutionDir) is undefined in the makefile build, so $(ProjectDir)\..\ must be used instead.
=> Fix error in keybind build when building from makefile.

blakcomp/blakcomp.h, blakserv/blakserv.h, blakserv/loadkod.c
Recent Blakod language changes mean there may be incompatibility when
using bof files built with previous versions of the compiler.
=> Increment BOF version to 6.

blakserv/adminfn.c, blakserv/async.c, blakserv/blakserv.h, blakserv/blakserv.vcxproj, blakserv/block.c, blakserv/block.h, blakserv/ccode.c, blakserv/config.c, blakserv/interface.c, blakserv/makefile, blakserv/session.c, blakserv/session.h, blakserv/synched.c, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/util/system.kod
Changes:
Blakserv is now initializing an IPv6 socket with IPv4 support ("dual stack socket"), rather than an IPv4 socket only. IPv6 addresses have 16 bytes (128-Bit) rather than the 4 bytes (32-Bit) of IPv4. Connected IPv4 addresses are also written in IPv6 notation.
Examples of connected IPv4 clients:
::ffff:127.0.0.1 (localhost IPv4 connection)
::ffff:153.25.125.2 (external IPv4 connection)
As you can see this is a mix of hexadecimal (ffff) IPv6 and decimal (127) IPv4 notation.
It is recommended to keep the notation to this in files like "banned.txt" or console commands. However internally these are all represented by 16 bytes (no matter which separator char is used).
So the GetIPString() KOD function will always return a possibly slighty different notation, like: …
=> IPv6 support in blakserv

kod/object/active/holder/nomoveon/battler/player.kod, kod/util/system.kod
FixSpellLevelChange will remove a spell from players and readd it if
they can learn it. Can be used when changing a spell level to make sure
only players who can learn the new level of the spell will have it. If
the spell isn't readded, the player is given the equivalent number of
training points for the % they had in the spell.
Added some code to the training point system in Player to get around the
1000 point cap if necessary. The cap will still be adhered to except if bCap
is sent with a FALSE value (i.e. by FixSpellLevelChange). The only other
difference is players can get above 1000 with their last kill that maxes their
training points (i.e. 1001, 1002, 1003 etc). The reasoning for this behavior
is that if the player receives some large TP reward (i.e. quest or tough
monster kill) …
=> Add message to fix players when changing spell level. Training point system modifications.

kod/object/item/passitem/token.kod
Token drop code needs to send player's fine coordinates to NewHold,
otherwise default values of 32 are used for finerow/finecol, which can
sometimes mean the token ends up in a wall.
=> Fix tokens dropping inside walls.

blakserv/time.c
Function needs to return DaylightBias instead of Bias if DST is active.
=> Allow GetTimeZoneOffset() to return correct DST offset.

kod/object/passive/spell/persench/karahol.kod
Will now last 8 seconds at LOW spellpower, and 2 seconds at HIGH spellpower. This makes using the spell at max spellpower better than at low, versus the situation now where the spell is practically useless at high %, as losing the effect via expiry or Purge holds the player for up to 16 seconds.
=> Reverse Kara'hol's hold effect, halve duration

clientd3d/bsp.h
Room editor could create polygons with more points (100) than the client would allocate space for (20), causing a crash if the room is loaded.
=> Increase client MAX_NPTS to match room editor value.

blakserv/roomdata.c, blakserv/roomdata.h
This list needed to be traversed every time a room ID lookup was needed,
thus was much better suited to a table.
Also added a separate table containing the resource id and room id, to
enable fast lookup of which rooms have been loaded by resource id (used
for rented rooms and survival arena, so they don't make duplicate rooms
but use existing data).
=> Convert roomdata storage from linked list to table.

kod/object/active/holder/nomoveon.kod, kod/object/active/holder/room/necarena.kod, kod/object/active/holder/room/tosrm/tosarena.kod, kod/object/passive/spell/discord.kod, kod/object/passive/spell/radiusench.kod
This adds a fourth parameter to Radius Enchantment information - the
source room. This helps differentiate between two old-style REs cast by
the same source in two different rooms. This prevents icon loss and
duplicates when moving between two rooms that have the same old-style
AE, same caster, and same spellpower.
=> Old-style RE specificity fix

kod/include/blakston.khd, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/passive/brain/makefile, kod/object/passive/brain/swarmbrain.kod, kod/util/system.kod
Same as normal brain, except sets the property for reducing hatred on players that already have aggro to 0. Kept the other (identical) properties to show current customization points.
=> Add "swarm brain" for mobs that always need to aggro.

clientd3d/bspload.c, clientd3d/move.c, clientd3d/move.h, clientd3d/room.h
The client could only move to the edge of the max row/cols, whereas now it needs to be able to move to the fineunit edge. The client will now load the things in the same manner as the server, and use them for room boundary checking. The server will move the player to the next screen when they hit the boundary.
=> Fix client not being able to move right to edge of things bbox.

blakcomp/function.c, clientd3d/audio.c, clientd3d/audio.h, clientd3d/server.c, clientd3d/server.h, include/proto.h, kod/include/protocol.khd, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room.kod, kod/util/nodeattk.kod
BP_STOP_WAVE will instruct the client to stop playing a given sound resource.
Added the rain.wav sound to room.kod, plays when rain is active. StartRain() adds the sound to the room's looping sounds, EndRain() removes it. AddLoopingSound() and RemoveLoopingSound() will update the players in the room.
=> Add BP_STOP_WAVE protocol to stop playing a sound, fix up looping sound infrastructure and add sound to StartRain().

kod/object/active/holder/nomoveon/battler.kod, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/player.kod
I know we've got lots of pulls in 1.0.16.0 but this is vital and pretty simple.
plHurtMeRecently keeps track of who dealt damage to players and monsters
recently. Each new instance of damage resets the timer. 20 seconds for
players, 60 seconds for monsters. When the timer runs out, you're no longer
in the list of who hurt this battler recently.
This'll help us know who actually logged or killed a player or monster. We can 
compare sum damage dealt and say, with certainty, something like:
[server message] Gar was just logged by Keen.
or if boss mobs get taken down, each player gets rewarded based on 
how much damage they dealt.
=> Damage Dealt Tracking

kod/object/active/holder/nomoveon/battler/player.kod, kod/util/system.kod
Users will soon be able to see the game year through the time command.  For lore reasons and possible future use, the year should be later than the years already recorded in various places such as the princess castle library. latest recorded date there is 715.
=> Add utility message to set the game year

blakserv/ccode.c
Removed some unused variables that were causing the nmake build to fail due to warnings treated as errors
=> Removed some unused variables

blakserv/account.c, blakserv/account.h, blakserv/adminfn.c, blakserv/user.c, blakserv/user.h
The admin command "delete unused" will remove any unused accounts (i.e.
any that have never been logged on before) and compact the account
numbers to reclaim previously used ones.
Kicks off all users before carrying out the delete/compact to avoid any
potential issues with sessions.
=> Add an admin command to clear out unused accounts and compact IDs.

kod/object/active/holder/room/ghall.kod
This prevents casting of conveyance inside the main portions of halls
except by the guild that owns it. Unowned, raided, and conquered halls
also prevent conveyance. This is to prevent any 'easy looting' shenanigans
until you actually fully own the hall.
builds, runs, tested in-game no errors or debug messages
=> No Conveyance in Halls

kod/object/active/holder/room/gallery.kod
Currently the underworld portal in the object gallery room takes you outside the underworld map.  Setting destination coordinates in the portal creation fixes this.
=> Set destination coordinates for gallery to UW portal

kod/object/passive/spell/sweep.kod
Sweep will no longer grab items between zones under any circumstances.
If the item is inside the hall and you are in the foyer, or if the item
is in the foyer and you are inside the hall, Sweep will ignore the item.
This is similar to the Conveyance tweak. I have looted halls this way in the past;
take stuff from the chest, drop it, and have a character in the foyer cast Sweep.
Sometimes you can be far enough away that people in the hall won't even
hear the spell. Other than that, it's just strange that halls would allow this while
preventing everything else (EQ, attacks, etc).
Additionally, Sweep allows riskless stocking of chests (item transfer without
opening the door).
built, tested in and out of multiple halls, and in normal zones, dm and mortal
=> No Sweeping between guild hall zones

kod/object/item/passitem/spelitem.kod, kod/object/passive/spell/brittle.kod
Wands, scrolls and potions now check spellpower modifiers on the caster (AmA, mana convergence and dement) and modify the item's spellpower if any of these are present.
Not having these spells affecting the items is an issue at the moment due to the prevalence of (especially) wands in PvP, which are more useful now with Ogre client targeting and the ability to stack hundreds of charges into a single item for ease of use.
Also fixed up brittle a bit, since it required a bound on min spellpower to handle the wand change (this would also throw an error if a player with 1 spellpower tried to cast the spell normally, but is rare enough to have not been seen yet).
=> Add spellpower mods (AmA, mana con, dement) to spellitems.

blakserv/ccode.c, blakserv/geometry.h, blakserv/roofile.c, blakserv/roofile.h
Rebased variant of: https://github.com/OpenMeridian/Meridian59/pull/1219
Improves and fixes things which get introduced in 1.0.16.0, therefore supposed to be part of 1.0.16.0
ac24783:
Improves BSPCanMoveInRoom by making it faster and fixing a possible small issue. Also fixes the formatting of this function (was tabs before)
16a72a4:
More a mini-style fix for an additional ;
83ae72b:
The calculation here was wrong, acosf() returned UNDEF most the time, because vectors were not normalized before. The fixed version did not behave noticeable different from removing it completely, so I did second.
777ec36:
Improves "GetStepTowards" move-heuristic.
=> Improve move heuristic, optimize BSPCanMoveInRoom, other fixes

kod/object/active/holder/nomoveon/battler/monster.kod
If a player had no shillings on them, the BankWithdraw message would both create the requested amount and then also give the player the money a second time lower in the message.
=> Fix banker dup bug

kod/object/active/holder/nomoveon.kod, kod/object/active/holder/room/necarena.kod, kod/object/active/holder/room/tosrm/tosarena.kod, kod/object/passive/spell/discord.kod, kod/object/passive/spell/radiusench.kod
Revert changes to radius enchantments - causes Jala spells to stay
active after user has left room. The RadiusEnchantment class needs
to be refactored so that rooms take care of placing these spells,
not the spell itself (i.e. in the same manner as RoomEnchantment).
=> Revert radius enchantment changes.

kod/object/active/holder/nomoveon/battler/monster/human.kod, kod/object/active/holder/nomoveon/battler/monster/human/troop.kod, kod/object/active/holder/nomoveon/battler/monster/human/troop/factionmage.kod, kod/object/active/holder/nomoveon/battler/monster/towns/jasprtwn/jasvaultm.kod, kod/object/active/holder/nomoveon/battler/monster/xeochctl.kod, kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeoearth.kod, kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeofire.kod, kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeoholy.kod, kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeoill.kod, kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeounholy.kod, kod/object/active/holder/nomoveon/battler/monster/xeochctl/xeowater.kod, kod/object/passive/spell/atakspel/radproj/firestorm.kod
These mobs need to set equipment before setting HP and any other level/difficulty based properties in Monster's constructor.
Raised level slightly on faction mages.
Xeos were a bit lackluster in the recent node attack, so increased speed on all to at least 18 (some are at 20).
Fix spelling in Japser vaultman description, change firestorm killed resource.
=> Fix Human/Troop constructors to set correct HP, speed up xeochicatls.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/nomoveon/battler/player/user/escapedconvict.kod, kod/object/passive/spell.kod
- Made Escaped Convict invisible to mortals on the who list
- Added a ResetEscapedConvict Message to boost stats, heal, give spells,
and equip an escaped convict before each event
- Added AdminHarm and AdminHeal messages to shorten or prolong an event
- added message to add equipment to an EC (currently only reagent bag if
he doesn't have one already
- Removed the need for reagents for EC
- Increased Max bulk and weight held to 1 million
- Can attack EC anytime anywhere including when pvp is turned off for the
server, but beware, EC can also fight back!
=> Upgrades to the escaped convict event actor class

kod/object/active/holder/nomoveon/battler/player/user/dm.kod, kod/util/system.kod
- dm systemmessage - typical system message including the [###] prefix
- dm gemote - replicates send users from within the admin window
- dm gqemote - same as above but overrides the notification sound
- dm lemote - replicates the echo command currently available (perhaps remove echo now?)
- dm lqemote - same as above without the notification sound.
=> dm system message and room message as dm commands

blakserv/geometry.h, blakserv/roofile.c, clientd3d/audio.c, clientd3d/client.h, kod/object/active/holder/nomoveon/battler.kod, kod/object/passive/spell/multicst/hunt.kod
When a monster's move will cross a wall, the point on the wall for the lines move_start->move_end and the wall line itself is calculated. Currently the X,Y values for this point are often incorrect by < 0.1, and if the end point is across a wall from the start point and the end point is very close to the wall, this will allow the monster to incorrectly move through it.
To fix this, the calculation is now done using doubles instead of floats (fixing cases where c1 is large). Some cases remained after this and to handle those, the ISINBOX macro now subtracts 0.1f from the min box value and adds 0.1f to the max box value to ensure the point is contained within.
* Fixed client crashes caused by having no sound devices connected to the computer.
* Fixed typo in minion removal code.
* Added …
=> Fix client audio issues, fix mobs walking through walls, misc. kod fixes.

blakserv/roofile.c, blakserv/roofile.h
Changes to BSPLineOfSight:
1) Reformatted from tabs to whitespaces
2) Use BSP splitter's A,B,C as a2,b2,c2 (faster, like in BSPCanMoveInRoom)
3) Move some code out of the wall loop (faster, like done in BSPCanMoveInRoom)
4) Use 'double' precision for calculating the intersection point.
5) Add 4 additional LoS checks for points slightly off in x, y directions if center check fails
=> Small LOS refactoring

blakserv/parsecli.c, blakserv/synched.c
Several of the ParseClientSendBlakod errors have been occurring on 103
and will now display more identifying information (protocol num, client
parameter, client version and account id) to allow us to track down the
errors.
=> Add more verbose error msgs to ParseClientSendBlakod.

kod/object/passive/spell/persench/detinvis.kod, kod/object/passive/spell/persench/eagleyes.kod, kod/object/passive/spell/persench/freeact.kod
As posted on the globe if you are caught unbuffed it is basically game over.
With no cast time u can quickly buff yourself and have a chance at safety or even defeating your attacker.
=> Remove cast timer from CC defenses

kod/object/active/holder/nomoveon/battler/monster/thrasher.kod, kod/object/passive/trestype/thrasht.kod
Remove enfeeble, it is nothing but aggervating. it serves no purpose.
Raised cashmin from -12000 to -9000. such tuff mobs shouldn't have such
a negative cash drop.
Made karma neutral so that qors may have a place to reach 150 without
destroing karma.
=> thrasher upgrades

blakserv/sendmsg.c
To ensure that data isn't written outside an object's property array, StoreValue must check lower (0) and upper (number of obj props) bounds when assigning data to a property.
Currently this is done using the number of properties taken from the object's class data structure, requiring the class to be obtained and checked to assign to the property. However, since objects already keep track of how many properties they have (o->num_props), this value can be used directly from the object itself, allowing the removal of the class-related code from StoreValue.
This provides a 10-15% performance increase when assigning data to a property (11% in the following benchmark).
https://gist.github.com/skittles1/cd5906a3de2ac0ef4508
All builds from clean, tried with several variations (number of …
=> Use object's num_props value for bounds checking when assigning data to a property in StoreValue.

kod/object/active/holder/nomoveon.kod, kod/object/active/holder/room.kod, kod/object/passive/spell.kod, kod/object/passive/spell/atakspel.kod, kod/object/passive/spell/roomench.kod, kod/object/passive/spell/roomench/darkness.kod, kod/object/passive/spell/roomench/forceslt.kod, kod/object/passive/spell/roomench/heat.kod, kod/object/passive/spell/roomench/heat.lkod, kod/object/passive/spell/roomench/killing.kod, kod/object/passive/spell/roomench/light.kod, kod/object/passive/spell/roomench/martyrs.kod, kod/object/passive/spell/roomench/qorbane.kod, kod/object/passive/spell/roomench/qorbane.lkod, kod/object/passive/spell/roomench/shalbane.kod, kod/object/passive/spell/roomench/shalbane.lkod, kod/object/passive/spell/roomench/silence.kod
* Renamed Spell's CheckPlayerAttack() to CheckPlayerAttackCast() to better reflect its purpose (checking attack status on cast rather than on effect).
* Added PKILL_ENABLE and temp safe checks to CheckPlayerAttackCast().
* Added RoomEnchantmentDamage() message in RoomEnchantment, handles all damaging room effects. Heat, Qorbane and ShalilleBane use this to apply damage. Uses AllowPlayerAttack() to determine whether any target will be damaged, also damages caster (can be toggled with vbRoomEnchHitCaster).
* Room enchantments that do damage now have similar code to attack spells - viAttack_spell to determine the damage type (e.g. fire, holy) and a ComputeDamage() message to calculate the damage.
* Damaging or killing players with room enchantments will now incur outlaw/murderer penalties.
* …
=> Check all worn items for heat damage, refactor room enchantment attack/damage code.

blakserv/roofile.c, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room/ghall/guildh6.kod
Ivory Chapel guild hall chest is in a small raised alcove, and currently
BSPLineOfSightTree returns false when a player tries to add or remove
items from this chest (DEBUGLOS reports a ceiling block). This appears
to happen because of the height adjustment to the end point's Z axis,
which adjusts for the object's (which is presumed to be a player or
monster) viewing height.
BSPLineOfSight will now call BSPLineOfSightTree an extra time with end
point coordinates and height adjustment +1 (floor height returns a
block) instead of 768 (player eye height), which fixes this issue.
Also changed the chest LoS check in user.kod to check from player->chest
rather than chest->player.
Raised the time the Ivory Chapel chest stays open from 10 seconds to 60.
=> Fix LoS issue with raised objects in small spaces.

kod/object/active/holder/room/monsroom/castle1b.kod, kod/object/active/holder/room/monsroom/objroom/castle1.kod
Players casting area damage spells from the safety of one area while
affecting other areas is still an issue in CV. This change allows
monsters to use the doors in main room CV again, and also disallows
attacking between different sections of the room. Attacks between
different sections of Upstairs CV are also blocked.
Mobs walking through the doors can be turned on/off with a property.
=> Re-add skeleton door usage in CV, disallow attacks.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/item.kod, kod/object/item/passitem/defmod/shield/soldshld.kod, kod/object/item/passitem/defmod/shield/soldshld/dukeshld.kod, kod/object/item/passitem/defmod/shield/soldshld/prinshld.kod, kod/object/item/passitem/defmod/shield/soldshld/reblshld.kod, kod/object/passive/spell.kod, kod/object/passive/spell/utility/phase.kod, kod/util/settings.kod
* New setting to restrict soldier shield specialized bonuses purely to
direct attacks and spells on other soldiers and mobs. This should prevent
scenario overlap that has proven to be a problem. Specifically,
this applies Cess shield's mana cost reduction only to spells with 1 
target that target a mob or enemy soldier; Duke shield's spellpower
bonus only adds to spells with 1 target that target a mob or enemy
soldier; Jonas shield only gives armor against mobs and enemy soldier
attacks. Why? Because this fixes a variety of scenario overlap problems.
Players have been complaining about 'stacking shields', and also that
murderers get soldier shields 'free' while hunters cannot use them for
character train reasons. This fixes both of those issues. If a murderer
has a soldier shield and you …
=> Soldier shield settings & fixes

blakserv/adminfn.c, blakserv/ccode.c, blakserv/roomdata.c, blakserv/roomdata.h, kod/include/blakston.khd, kod/object/active/holder/nomoveon/battler/monster.kod, kod/object/active/holder/nomoveon/battler/monster/human/troop/necrotr.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/room.kod, kod/object/active/holder/room/monsroom/guest6.kod, kod/object/active/holder/room/monsroom/uworld.kod, kod/object/active/portal/hellport.kod, kod/object/item/passitem/defmod/shield/soldshld/necshield.kod, kod/object/item/passitem/qormasgift.kod, kod/object/passive/brain.kod, kod/object/passive/flikerer/bswitch.kod, kod/object/passive/guild.kod, kod/object/passive/itematt/weapatt/wafactn.kod, kod/object/passive/spell/teleportspell/deathrift.kod, kod/util/factgame/territry.kod, kod/util/gameevent.kod, kod/util/gameevent/qormas.kod, kod/util/gameeventengine.kod, kod/util/parlia.kod, kod/util/realtime.kod
Added necromancer faction constant. Necromancer soldier shields need to have their own faction constant to be equippable by necromancer troops (which should also have the same faction constant). This constant isn't used for anything else at the moment.
Allow DMs to offer items to monsters - these items go in the monsters' plPassive list, and will be dropped upon the monster's death. Allows faster setting up during events.
Fix uninitialized variable in VaultWithdrawl (needs to start as FALSE, not the default $).
* Room 'blockers' are tied to the roomdata so duplicate rooms can no longer reuse roomdata. Creating a duplicate room will now load a copy of that room from disk. We should likely improve this later to keep a master copy of each available room in memory and load from this for …
=> Fix necro troop soldier shield issue, allow DMs to offer items to mobs to set up events easier. Misc bug fixes.

blakserv/sendmsg.c, blakserv/sendmsg.h, include/bkod.h
Added a bkod_type data type which is typedefed to the kod data type (i.e. tag + data). Currently this is just 'int', however having this defined and using it wherever a kod data type is defined as an integer will make the future switch to 64-bit much easier.
Added structs to hold the dest and source variables for unary and binary ops, so they can be read from interpreted blakod in one read compared to two or three. Provides a 7.5% performance increase on those two calls (test message temporarily added to this pull request).
Removed the call timing related ifdefs from the interpreter - now GetMicroCountDouble() is called instead of QPC. This cancels out most of the performance improvement from the previous commit, but increases readability in the interpreter and means the ifdef'd code is …
=> Interpreter optimization, call timing ifdef removal, add bkod_type data type.

kod/object/active/wallelem/asburstc.kod, kod/object/passive/spell/walspell/rngflame.kod, kod/object/passive/spell/walspell/sporbrst.kod
* Sporeburst now has a setting to make it a targetable spell (like RoF). Setting is off by default (also added the setting to RoF).
* Sporeburst hold time now matches that of the spell, rather than always being 6+ seconds (spell is 3-6 seconds).
* Sporeburst hold chance is now base 40% + spellpower/2. In practice, players will always get held a few times before they can exit the cloud but the time can be adjusted live (i.e. we can start with similar to current behavior and adjust down if necessary).
=> Allow sporeburst to be targeted (default for this is off), adjust hold time/chance.

blakserv/sprocket.c, include/proto.h, kod/include/blakston.khd, kod/include/protocol.khd, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod, kod/object/active/holder/nomoveon/battler/player/user/dm.kod, kod/object/active/holder/nomoveon/battler/player/user/dm.lkod, kod/object/active/holder/room.kod, kod/object/passive/news.kod, kod/object/passive/spell/atakspel/earthqua.kod, kod/object/passive/spell/teleportspell/deathrift.lkod, kod/util/settings.kod, module/mailnews/mailnews.c, module/mailnews/mailnews.h, module/mailnews/mailnews.rc, module/mailnews/mailnews.vcxproj, module/mailnews/mailnews.vcxproj.filters, module/mailnews/mailnwrc.h, module/mailnews/newsread.c
* Added a Delete button to all newsglobes. Anyone can click on it, but only DMs and above will be able to remove posts by default. A setting has been added to allow users to remove their own posts. Button is present in German and English versions of the classic client.
* Posts removed from newsglobes will be moved to the God Globe in room 901 instead of deleting them. Posts deleted from there will be properly deleted.
* Removed unnecessary variables from user.kod's ReceiveClient.
* Allow BP_REQ_QUIT protocol messages to bypass the packet throttle in ReceiveClient.
* Users must delete their posts within 1hr of posting, otherwise they will be unable to do so. Default time can be adjusted.
* Increased server chat (broadcast/say/tell etc.) string length limit from 500 to 550. Classic client …
=> Add Delete Post button to newsglobes. Move deleted posts to god globe. Misc bug fix/improvement PR.

kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod
EvilTwin class is used for monsters now instead of a copy of that monster, so they shouldn't always call IsLoggedOn on the original.
=> Fix IsLoggedOn calls to mob originals in ET.

kod/object/active/holder/nomoveon/battler/player.kod, kod/object/active/holder/nomoveon/battler/player/user.kod
Casters will lose their ETs on entering any safe room (the previous fix
enabled this only for Inns/adv halls and not shops etc.).
Attacks on minions now use the correct room (minion's room) and not the
master/caster's room as in the case of ET this breaks down, specifically
for guilded vs. non-guilded screens given the above change to ET
deletion.
=> Kill caster's ETs in any safe room, fix attacks on minions.

kod/object/active/holder/nomoveon/battler.kod, kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod, kod/object/active/holder/room/monsroom/survivalroom.kod
- ET's GotoOriginal should return without teleporting the ET if the ET
has no poCaster or poMaster.
- Changed Battler.RemoveEvilTwin() to ClearEvilTwin() as the ET itself
is not removed or deleted by this message, only the property cleared.
- Performance improvements in SurvivalRoom due to continuing high CPU
usage.
=> Clear ETs correctly on "leave survival" command, performance improvements to SurvivalRoom.

blakserv/database.c, blakserv/synched.c
Not doing so can lead to player name being freed later on, crashing the server.
=> Duplicate player name for database entry.

blakcomp/actions.c, blakcomp/sort.c, blakserv/sendmsg.c
Duplicate parameters were being checked using the current message ID for
comparison, however as the parameters are parsed before the message
header, these message IDs referred to the previous message.
This works fine nearly all the time (and the message ID isn't used for
anything else by the parameters) however if a set of parameters is being
parsed and the previous message in that class has a copy in another
(parsed in this batch) class followed by a message containing a
parameter with the same name, the compiler will return a false positive
for a duplicate parameter.
This change removes the duplicate check during parameter parsing and
moves it to the parameter list sorting.
The existing code worked for simple calculations however trying to use
the prefix/postfix operators in complex …
=> Fix compiler and prefix/postfix operator errors.

blakcomp/blakcomp.l
We will potentially be using Doxygen or other codedoc program to
generate documentation from the codebase, and generating useful docs
will require the ability to comment kod code with multi-line comments.
The % style comments have been left intact, and support for both //
single line and /* */ multi-line comments has been added. Neither are
active inside strings, otherwise comments can be placed anywhere (source
is compiled as if they are not there at all, the lexer removes them).
Multi-line comments can be nested (making /* /* \*/ \*/ a valid comment)
but // takes precedence and can 'comment out' an /* inside a comment
block.
Changed yyerror to exit as continuing to parse after this kind of error can
cause the compiler to crash.
Flex state changes now use the state stack rather than …
=> Add /**/ (multi-line) and // style comments to kod, add region folding (for supported editors).

kod/kod.mak, kod/makefile, kod/object/active/holder/nomoveon/battler/monster/deadlich.kod, kod/object/active/holder/nomoveon/battler/monster/towns/jasprtwn/makefile, kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcbonepr.kod, kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcshopk.kod, kod/object/active/holder/room/monsroom/makefile, kod/object/item/passitem/numbitem/reagent/makefile, kod/object/item/passitem/spelitem/scroll/makefile, kod/object/passive/brain/makefile, kod/object/passive/itematt/makefile, kod/object/passive/makefile, kod/object/passive/skill/stroke/unarmed/makefile
BOFS2 variable is only used once, 3-8 not at all. I'm guessing at some point in the past the number of files to one nmake variable was limited, or perhaps they were used for neater formatting in the makefiles. Either way, they aren't needed.
Also prevented the output of the bc.exe command (just the command itself, not any error messages generated) from being displayed as it makes the errors easier to spot.
Removed some missing bof references from makefiles and added some (commented) bofs from kods that are present but not used.
Fixed some incorrect resources in a couple files.
=> Small kod makefile cleanup, fix some incorrect resources.

clientd3d/d3drender.c, clientd3d/d3drender.h, clientd3d/drawbmp.c, clientd3d/object3d.c, clientd3d/object3d.h
This handles a missing case in the overlay system - overlays that should
be drawn on top of a base item, but underneath underlays drawn on other
overlays on the base item.
Software renderer handles this by drawing the new type of overlay before
any other overlays are drawn on the base item. Hardware does the same
but also has to set a Z bias equal to that of the base item to avoid
rendering the overlay in the wrong place.
Reproduced the kod hotspot index constants in object3d.h, HS_HELM is
used in FindHotspotPdib rather than using '2'.
=> Fix overlay drawing for new helm.

kod/util/realtime.kod
Year-day wasn't rolling over at the end of each year (needs to mod by
diff amount depending on leap year).
Day also wasn't returning the correct value (same calc).
GetYear still doesn't account correctly for leap years, and I think the
solution here is probably to have a C call that returns time as either a
string, a list or an int (YYYYMMDD only) and use it that way.
=> Fix year/day handling in RealTime.
